[module]
name        = "{{MODULE_NAME}}"
description = "Write a short description here"
version     = "1.0.0"
deps        = []
#deps = [{ name = "example", version = ">=1.0.0", source = "user/repo" }]
tags        = []
requires_cmd     = []
requires_any_cmd = []
implicit    = false

[api]
functions  = ["help_{{MODULE_NAME}}"]
variables  = []
defer_on_cmd = true
# aliases      = { top = "btop" }
# completions  = { "help_{{MODULE_NAME}}" = "_files" }
