use super::types::{DiscoveredModule, ModuleStatus};
use super::Loader;
use anyhow::Result;

impl Loader {
   pub fn generate_init_from(&self, modules: &[DiscoveredModule]) -> Result<String> {
        let mut out = String::new();

        out.push_str("# Auto-generated by gaiety\n\n");
        out.push_str(&self.generate_reset_fn(modules));

        let wrapper_template = include_str!("../templates/wrapper.zsh");
        out.push_str(wrapper_template);

        out.push_str("\n# --- Load Modules ---\n");
        let mut all_completions = Vec::new();

        for m in modules {
            if m.status == ModuleStatus::Loaded {
                let init_script = m.path.join("init.zsh");
                if init_script.exists() {
                   out.push_str(&format!(
                        "source '{}'\n",
                        sq_escape(&init_script.display().to_string())
                    ));
                }

                for (name, expansion) in &m.manifest.api.aliases {
                   out.push_str(&format!(
                        "alias '{}='{}'\n",
                        sq_escape(name),
                        sq_escape(expansion)
                    ));
                }

                for (cmd, comp_fn) in &m.manifest.api.completions {
                    all_completions.push(format!(
                        "compdef {} {}",
                        sq_escape(comp_fn),
                        sq_escape(cmd)
                    ));
                }
            }
        }

        if !all_completions.is_empty() {
            out.push_str("\n# --- Completions ---\n");
            out.push_str("if type compdef &>/dev/null; then\n");
            for comp in all_completions {
                out.push_str(&format!("  {}\n", comp));
            }
            out.push_str("fi\n");
        }

        Ok(out)
    }

    fn generate_reset_fn(&self, modules: &[DiscoveredModule]) -> String {
        let mut out = String::new();
        out.push_str("_gai_reset() {\n");

        let mut all_funcs: Vec<String> = Vec::new();
        let mut all_vars: Vec<String> = Vec::new();
        let mut all_aliases: Vec<String> = Vec::new();

        for m in modules {
            if m.status == ModuleStatus::Loaded {
                all_funcs.extend(m.manifest.api.functions.iter().cloned());
                all_vars.extend(m.manifest.api.variables.iter().cloned());
                all_aliases.extend(m.manifest.api.aliases.keys().cloned());
            }
        }

        if !all_funcs.is_empty() {
            let quoted = all_funcs.iter().map(|f| format!("'{}'", sq_escape(f))).collect::<Vec<_>>().join(" ");
            out.push_str(&format!("  unset -f {} 2>/dev/null\n", quoted));
        }
        if !all_vars.is_empty() {
            let quoted = all_vars.iter().map(|v| format!("'{}'", sq_escape(v))).collect::<Vec<_>>().join(" ");
            out.push_str(&format!("  unset {} 2>/dev/null\n", quoted));
        }
        if !all_aliases.is_empty() {
            let quoted = all_aliases.iter().map(|a| format!("'{}'", sq_escape(a))).collect::<Vec<_>>().join(" ");
            out.push_str(&format!("  unalias {} 2>/dev/null\n", quoted));
        }

        out.push_str("}\n");
        out
    }
}

fn sq_escape(s: &str) -> String {
    s.replace('\'', r"'\''")
}
