use crate::core::Loader;
use crate::core::manifest::{ApiMeta, Manifest};
use crate::core::types::{DiscoveredModule, ModuleStatus};
use anyhow::Result;
use std::collections::HashMap;

impl Loader {
    const GAIETY_HEADER: &str = "# Auto-generated by Gaiety\n\n";

    pub fn generate_init(&self, modules: &[DiscoveredModule]) -> Result<String> {
        let mut output = String::new();

        output.push_str(Self::GAIETY_HEADER);
        output.push_str(&self.reset_fn(modules));

        for function_body in modules
            .iter()
            .filter(|module| module.status == ModuleStatus::Loaded)
            .filter_map(Helper::reset_fn)
        {
            output.push_str(&function_body);
        }

        output.push_str(&Helper::render_wrapper());
        output.push_str("\n# --- Load Modules ---\n");

        let mut all_completions = Vec::new();
        let stages = Helper::partition_stages(modules);

        for (stage_index, stage) in stages.iter().enumerate() {
            let (lazy, eager): (Vec<_>, Vec<_>) = stage
                .iter()
                .copied()
                .filter(|module| module.path.join("init.zsh").exists())
                .partition(|module| module.manifest.api.defer_on_cmd);

            for module in lazy {
                output.push_str(&Helper::deferred_loader(module));
            }

            output.push_str(&Helper::eager_loader(stage_index, &eager));

            for module in stage {
                for (command, completion_function) in &module.manifest.api.completions {
                    output.push_str(&format!(
                        "compdef {} {}",
                        Helper::sq_escape(completion_function),
                        Helper::sq_escape(command)
                    ));
                    all_completions.push(format!(
                        "compdef {} {}",
                        Helper::sq_escape(completion_function),
                        Helper::sq_escape(command)
                    ));
                }
            }
        }

        output.push_str(&Helper::generate_completions(&all_completions));
        Ok(output)
    }

    pub fn reset_fn(&self, modules: &[DiscoveredModule]) -> String {
        let mut output = String::new();
        output.push_str("_gai_reset() {\n");

        let mut all_functions = Vec::new();
        let mut all_variables = Vec::new();
        let mut all_aliases = Vec::new();

        for module in modules {
            if module.status == ModuleStatus::Loaded {
                all_functions.extend(module.manifest.api.functions.iter().map(String::as_str));
                all_variables.extend(module.manifest.api.variables.iter().map(String::as_str));
                all_aliases.extend(module.manifest.api.aliases.keys().map(String::as_str));
                all_functions.extend(module.manifest.api.aliases.keys().map(String::as_str));
            }
        }

        if !all_functions.is_empty() {
            output.push_str(&format!(
                "  unset -f {} 2>/dev/null\n",
                Helper::quote_escape(&all_functions)
            ));
        }

        if !all_variables.is_empty() {
            output.push_str(&format!(
                "  unset {} 2>/dev/null\n",
                Helper::quote_escape(&all_variables)
            ));
        }

        if !all_aliases.is_empty() {
            output.push_str(&format!(
                "  unalias {} 2>/dev/null\n",
                Helper::quote_escape(&all_aliases)
            ));
        }

        output.push_str("}\n");
        output
    }
}

struct Helper;

impl Helper {
    const DEFAULT_EXE_NAME: &str = "gaiety";

    fn quote_escape<I, S>(items: I) -> String
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
        items
            .into_iter()
            .map(|string| format!("'{}'", Self::sq_escape(string.as_ref())))
            .collect::<Vec<_>>()
            .join(" ")
    }

    fn sq_escape(s: &str) -> String {
        s.replace('\'', r"'\''")
    }

    fn partition_stages<'a>(modules: &'a [DiscoveredModule]) -> Vec<Vec<&'a DiscoveredModule>> {
        let mut stages: Vec<Vec<&DiscoveredModule>> = Vec::new();
        let mut named = HashMap::new();

        for module in modules {
            if module.status != ModuleStatus::Loaded {
                continue;
            }

            let mut max_dep = 0;
            let mut has_dependencies = false;

            for dependency in &module.manifest.module.deps {
                if let Some(&stage_index) = named.get(dependency.name.as_str()) {
                    max_dep = max_dep.max(stage_index);
                    has_dependencies = true;
                }
            }

            let stage_index = if has_dependencies { max_dep + 1 } else { 0 };
            named.insert(module.manifest.module.name.as_str(), stage_index);

            while stages.len() <= stage_index {
                stages.push(Vec::new());
            }
            stages[stage_index].push(module);
        }
        stages
    }

    fn reset_fn(module: &DiscoveredModule) -> Option<String> {
        let api = &module.manifest.api;

        if Self::check_empty(api) {
            return None;
        }

        let mut output = String::new();
        output.push_str(&Self::reset_stub(&module.manifest.module.name));

        let f_to_unset: Vec<&str> = api
            .functions
            .iter()
            .map(String::as_str)
            .chain(api.aliases.keys().map(String::as_str))
            .collect();

        Self::emit_unset(&mut output, "unset -f", f_to_unset);
        Self::emit_unset(&mut output, "unset", &api.variables);
        Self::emit_unset(&mut output, "unalias", api.aliases.keys());

        output.push_str("}\n");
        Some(output)
    }

    fn deferred_loader(module: &DiscoveredModule) -> String {
        let mut output = String::new();
        let init_script = module.path.join("init.zsh");
        let loader_fn = Self::deferred_stub(&module.manifest.module.name);

        let mut to_unfunction: Vec<&str> = vec![&loader_fn];
        to_unfunction.extend(module.manifest.api.functions.iter().map(String::as_str));
        to_unfunction.extend(module.manifest.api.aliases.keys().map(String::as_str));
        to_unfunction.extend(module.manifest.api.completions.values().map(String::as_str));

        let unfunction_list = Self::quote_escape(to_unfunction);

        output.push_str(&format!("{}() {{\n", loader_fn));
        output.push_str(&format!("  unfunction {} 2>/dev/null\n", unfunction_list));
        output.push_str(&format!(
            "  source '{}'\n",
            Self::sq_escape(&init_script.display().to_string())
        ));

        for (name, expansion) in &module.manifest.api.aliases {
            output.push_str(&format!(
                "  alias '{}={}'\n",
                Self::sq_escape(name),
                Self::sq_escape(expansion)
            ));
        }
        output.push_str("}\n");

        for function in &module.manifest.api.functions {
            let escaped_function = Self::sq_escape(function);
            output.push_str(&format!("unalias '{}' 2>/dev/null\n", escaped_function));
            output.push_str(&format!("{}() {{\n", escaped_function));
            output.push_str(&format!("  {}\n", loader_fn));
            output.push_str(&format!("  '{}' \"$@\"\n", escaped_function));
            output.push_str("}\n");
        }

        for alias in module.manifest.api.aliases.keys() {
            let escaped_alias = Self::sq_escape(alias);
            output.push_str(&format!("unalias '{}' 2>/dev/null\n", escaped_alias));
            output.push_str(&format!("{}() {{\n", escaped_alias));
            output.push_str(&format!("  {}\n", loader_fn));
            output.push_str(&format!("  eval '{} \"$@\"'\n", escaped_alias));
            output.push_str("}\n");
        }

        let mut unique_completions = module.manifest.api.completions.values().collect::<Vec<_>>();
        unique_completions.sort();
        unique_completions.dedup();

        for completion_fn in unique_completions {
            let escaped_completion = Self::sq_escape(completion_fn);
            output.push_str(&format!(
                "if ! type '{}' &>/dev/null; then\n",
                escaped_completion
            ));
            output.push_str(&format!("  unalias '{}' 2>/dev/null\n", escaped_completion));
            output.push_str(&format!("  {}() {{\n", escaped_completion));
            output.push_str(&format!(
                "    unfunction '{}' 2>/dev/null\n",
                escaped_completion
            ));
            output.push_str(&format!("    {}\n", loader_fn));
            output.push_str(&format!("    '{}' \"$@\"\n", escaped_completion));
            output.push_str("  }\n");
            output.push_str("fi\n");
        }

        output
    }

    fn eager_loader(stage_index: usize, eager: &[&DiscoveredModule]) -> String {
        let mut output = String::new();

        if eager.is_empty() {
            return output;
        }

        output.push_str(&format!("# --- Stage {} ---\n", stage_index));
        for module in eager {
            let init_script = module.path.join("init.zsh");
            output.push_str(&format!(
                "source '{}'\n",
                Self::sq_escape(&init_script.display().to_string())
            ));

            for (name, expansion) in &module.manifest.api.aliases {
                output.push_str(&format!(
                    "alias '{}={}'\n",
                    Self::sq_escape(name),
                    Self::sq_escape(expansion)
                ));
            }
        }

        output
    }

    fn generate_completions(completions: &[String]) -> String {
        let mut output = String::new();

        if completions.is_empty() {
            return output;
        }

        output.push_str("\n# --- Completions ---\n");
        output.push_str("if type compdef &>/dev/null; then\n");
        for completion in completions {
            output.push_str(&format!("  {}\n", completion));
        }
        output.push_str("fi\n");
        output
    }

    fn check_empty(module_api: &ApiMeta) -> bool {
        module_api.functions.is_empty()
            && module_api.variables.is_empty()
            && module_api.aliases.is_empty()
    }

    fn reset_stub(name: &str) -> String {
        format!("_gai_reset_{}() {{\n", name)
    }

    fn deferred_stub(name: &str) -> String {
        format!("_gai_load_deferred_{}", name)
    }

    fn emit_unset<I, S>(out: &mut String, command: &str, items: I)
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
        let items: Vec<_> = items.into_iter().collect();
        if !items.is_empty() {
            out.push_str(&format!(
                "  {} {} 2>/dev/null\n",
                command,
                Self::quote_escape(items),
            ));
        }
    }

    fn exe_path() -> String {
        std::env::current_exe()
            .map(|path| path.display().to_string())
            .unwrap_or_else(|_| Self::DEFAULT_EXE_NAME.to_string())
    }

    fn render_wrapper() -> String {
        let bin = &Helper::exe_path();
        include_str!("../templates/wrapper.zsh").replace("{{GAIETY_BIN}}", bin)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::manifest::Manifest;
    use std::path::PathBuf;

    #[test]
    fn test_sq_escape() {
        assert_eq!(Helper::sq_escape("hello"), "hello");
        assert_eq!(Helper::sq_escape("don't"), r"don'\''t");
    }

    #[test]
    fn test_generate_reset_fn() {
        let loader = Loader { dirs: vec![] };
        let mut m = DiscoveredModule {
            path: PathBuf::from("/tmp"),
            manifest: Manifest::broken("test".to_string()),
            prefix_order: None,
            dir_index: 0,
            status: ModuleStatus::Loaded,
        };
        m.manifest.api.functions = vec!["foo".to_string()];
        m.manifest.api.variables = vec!["BAR".to_string()];

        let reset_script = loader.reset_fn(&[m]);
        assert!(reset_script.contains("unset -f 'foo'"));
        assert!(reset_script.contains("unset 'BAR'"));
    }
}
