use std::collections::HashMap;
use std::default;

use crate::core::manifest::{ApiMeta, Manifest};
use crate::core::types::{DiscoveredModule, ModuleStatus};
use crate::core::{Loader, manifest};
use crate::emitter::zsh::DeclarationType::{Alias, Variable};
use anyhow::Result;

impl Loader {
    const GAIETY_HEADER: &str = "# Auto-generated by Gaiety\n\n";

    pub fn generate_init(&self, modules: &[DiscoveredModule]) -> Result<String> {
        let mut output = String::new();

        output.push_str(Self::GAIETY_HEADER);

        Ok(output)
    }
}

enum DeclarationType {
    Function,
    Variable,
    Alias,
}

struct Helper;

impl Helper {
    const DEFAULT_EXE_NAME: &str = "gaiety";

    fn quote_escape<I, S>(items: I) -> String
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
        let closure = |string: S| format!("'{}'", Self::sq_escape(string.as_ref()));
        items.into_iter().map(closure).collect::<Vec<_>>().join(" ")
    }

    fn sq_escape(s: &str) -> String {
        s.replace('\'', r"'\''")
    }

    fn partition_stages<'a>(modules: &'a [DiscoveredModule]) -> Vec<Vec<&'a DiscoveredModule>> {
        let mut stages: Vec<Vec<&DiscoveredModule>> = Vec::new();
        let mut named = std::collections::HashMap::new();

        for module in modules {
            if module.status != ModuleStatus::Loaded {
                continue;
            }

            let mut max_dep = 0;
            let mut has_dependencies = false;

            for dependency in &module.manifest.module.deps {
                if let Some(&stage_index) = named.get(&dependency.name) {
                    max_dep = max_dep.max(stage_index);
                    has_dependencies = true;
                }
            }

            let stage_index = if has_dependencies { max_dep + 1 } else { 0 };
            named.insert(module.manifest.module.name.clone(), stage_index);

            while stages.len() <= stage_index {
                stages.push(Vec::new());
            }
            stages[stage_index].push(module);
        }
        stages
    }

    fn reset_fn(module: &DiscoveredModule) -> Option<String> {
        let api = &module.manifest.api.clone;

        if Self::check_empty(&api) {
            return None;
        }

        let mut output = String::new();
        let function_declaration = Self::reset_stub(&module.manifest.module.name);
        output.push_str(&function_declaration);

        let mut f_to_unset = api.functions.clone();
        f_to_unset.extend(api.aliases.keys().cloned());

        if !f_to_unset.is_empty() {
            Self::emit_unset(&mut output, "unset -f", f_to_unset);
        }

        if !api.variables.is_empty() {
            Self::emit_unset(&mut output, "unset", &api.variables);
        }

        if !api.aliases.is_empty() {
            Self::emit_unset(
                &mut output,
                "unalias",
                api.aliases.keys().map(String::as_str),
            );
        }

        output.push_str("}\n");
        Some(output)
    }

    fn deferred_loader(module: &DiscoveredModule) -> String {
        let mut output = String::new();
        let init_script = module.path.join("init.zsh");
        let loader_fn = Self::deferred_stub(&module.manifest.module.name);

        let mut to_unfunction = vec![loader_fn.clone()];
        to_unfunction.extend(module.manifest.api.functions.iter().cloned());
        to_unfunction.extend(module.manifest.api.aliases.keys().cloned());
        to_unfunction.extend(module.manifest.api.completions.values().cloned());

        let unfunction_list = Self::quote_escape(to_unfunction);

        output.push_str(&format!("{}() {{\n", loader_fn));
        output.push_str(&format!("  unfunction {} 2>/dev/null\n", unfunction_list));
        output.push_str(&format!(
            "  source '{}'\n",,
            Self::sq_escape(&init_script.display().to_string())
        ));

        for (name, expansion) in &module.manifest.api.aliases {
            output.push_str(&format!(
                "  alias '{}={}'\n",
                Self::sq_escape(name),
                Self::sq_escape(expansion)
            ));
        }
        output.push_str("}\n");
        todo!()
    }

    fn check_empty(module_api: &ApiMeta) -> bool {
        module_api.functions.is_empty()
            && module_api.variables.is_empty()
            && module_api.aliases.is_empty()
    }

    fn reset_stub(name: &str) -> String {
        format!("_gai_reset_{}() {{\n", name)
    }

    fn deferred_stub(name: &str) -> String {
        format!("_gai_load_deferred_{}", name)
    }

    fn emit_unset<I, S>(out: &mut String, command: &str, items: I)
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
        let items: Vec<_> = items.into_iter().collect();
        if !items.is_empty() {
            out.push_str(&format!(
                "  {} {} 2>/dev/null\n",
                command,
                Self::quote_escape(items),
            ));
        }
    }

    fn exe_path() -> String {
        let closure = |_| Self::DEFAULT_EXE_NAME.to_string();
        std::env::current_exe()
            .map(|path| path.display().to_string())
            .unwrap_or_else(closure)
    }

    fn render_wrapper() -> String {
        let bin = &Helper::exe_path();
        include_str!("../templates/wrapper.zsh").replace("{{GAIETY_BIN}}", bin)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::manifest::Manifest;
    use std::path::PathBuf;

    #[test]
    fn test_sq_escape() {
        assert_eq!(Helper::sq_escape("hello"), "hello");
        assert_eq!(Helper::sq_escape("don't"), r"don'\''t");
    }

    #[test]
    fn test_generate_reset_fn() {
        let loader = Loader { dirs: vec![] };
        let mut m = DiscoveredModule {
            path: PathBuf::from("/tmp"),
            manifest: Manifest::broken("test".to_string()),
            prefix_order: None,
            dir_index: 0,
            status: ModuleStatus::Loaded,
        };
        m.manifest.api.functions = vec!["foo".to_string()];
        m.manifest.api.variables = vec!["BAR".to_string()];

        let reset_script = loader.generate_reset_fn(&[m]);
        assert!(reset_script.contains("unset -f 'foo'"));
        assert!(reset_script.contains("unset 'BAR'"));
    }
}
