use crate::core::loader::Loader;
use crate::core::manifest::ApiMeta;
use crate::core::types::{DiscoveredModule, ModuleStatus};
use anyhow::Result;
use std::collections::{BTreeMap, BTreeSet, HashMap};

impl Loader {
    const INIT_HEADER: &str = "# Auto-generated by Gaiety\n\n";

    pub fn generate_init(&self, modules: &[DiscoveredModule]) -> Result<String> {
        let mut output = String::new();

        output.push_str(Self::INIT_HEADER);
        output.push_str(&self.reset_fn(modules));

        for function in modules
            .iter()
            .filter(|module| module.status == ModuleStatus::Loaded)
            .filter_map(Helper::reset_fn)
        {
            output.push_str(&function);
        }

        output.push_str(&Helper::render_wrapper());
        output.push_str("\n# --- Load Modules ---\n");

        let mut completions = Vec::new();
        self.emit_stage_loaders(&mut output, modules, &mut completions);
        self.emit_event_dispatchers(&mut output, modules);

        output.push_str(&Helper::generate_completions(&completions));
        Ok(output)
    }

    fn emit_stage_loaders(
        &self,
        output: &mut String,
        modules: &[DiscoveredModule],
        completions: &mut Vec<String>,
    ) {
        let stages = Helper::partition_stages(modules);

        for (stage_idx, stage) in stages.iter().enumerate() {
            let mut eager = Vec::new();
            let mut lazy = Vec::new();
            let mut event = Vec::new();

            for module in stage
                .iter()
                .copied()
                .filter(|module| module.path.join("init.zsh").exists())
            {
                match module.manifest.load_mode() {
                    crate::core::manifest::LoadMode::Eager => eager.push(module),
                    crate::core::manifest::LoadMode::Lazy => lazy.push(module),
                    crate::core::manifest::LoadMode::Event => event.push(module),
                }
            }

            for module in lazy {
                output.push_str(&Helper::module_loader(module));
            }

            for module in event {
                output.push_str(&Helper::module_loader(module));
            }

            output.push_str(&Helper::eager_loader(stage_idx, &eager));

            for module in stage {
                for (command, completion) in &module.manifest.api.completions {
                    let escaped_completion = Helper::sq_escape(completion);
                    let escaped_command = Helper::sq_escape(command);
                    output.push_str(&format!(
                        "compdef {} {}",
                        escaped_completion, escaped_command
                    ));
                    completions.push(format!(
                        "compdef {} {}",
                        escaped_completion, escaped_command
                    ));
                }
            }
        }
    }

    fn emit_event_dispatchers(&self, output: &mut String, modules: &[DiscoveredModule]) {
        let mut subscribers: BTreeMap<String, Vec<(String, &DiscoveredModule)>> = BTreeMap::new();

        for module in modules {
            let loaded = module.status == ModuleStatus::Loaded;
            let event_mode = module.manifest.load_mode() == crate::core::manifest::LoadMode::Event;

            if loaded && event_mode {
                if let Some(ref load) = module.manifest.load {
                    for event in &load.events {
                        let native_hook = if event.starts_with("periodic") {
                            "periodic".to_string()
                        } else {
                            event.clone()
                        };
                        subscribers
                            .entry(native_hook)
                            .or_default()
                            .push((event.clone(), module));
                    }
                }
            }
        }

        if subscribers.is_empty() {
            return;
        }

        output.push_str("\n# --- Event Dispatchers ---\n");
        output.push_str("autoload -Uz add-zsh-hook\n\n");

        for (hook, subs) in &subscribers {
            output.push_str(&format!("_gai_dispatch_{}() {{\n", hook));

            if hook == "periodic" {
                output.push_str("  local now=$EPOCHSECONDS\n");
                for (event, module) in subs {
                    let interval: u64 = event
                        .split_once(':')
                        .and_then(|(_, second)| second.trim().parse().ok())
                        .unwrap_or(10);

                    let name = &module.manifest.module.name;
                    let last_run = format!("_gai_last_run_{}_{}", name, interval);
                    let loader_name = format!("_gai_load_module_{}", name);
                    let callback_name = format!("_gai_event_{}_periodic_{}", name, interval);

                    output.push_str(&format!(
                        "  if (( now - {} >= {} )); then\n",
                        last_run, interval
                    ));
                    output.push_str(&format!("    {}=now\n", last_run));
                    output.push_str(&format!("    {}\n", loader_name));
                    output.push_str(&format!(
                        "    if typeset -f {} >/dev/null 2>&1; then\n",
                        callback_name
                    ));
                    output.push_str(&format!("      {} \"$@\"\n", callback_name));
                    output.push_str("    fi\n");
                    output.push_str("  fi\n");
                }
            } else {
                for (event, module) in subs {
                    let name = &module.manifest.module.name;
                    let loader_name = format!("_gai_load_module_{}", name);
                    let suffix = event.replace(':', "_");
                    let callback_name = format!("_gai_event_{}_{}", name, suffix);

                    output.push_str(&format!("  {}\n", loader_name));
                    output.push_str(&format!(
                        "  if typeset -f {} >/dev/null 2>&1; then\n",
                        callback_name
                    ));
                    output.push_str(&format!("    {} \"$@\"\n", callback_name));
                    output.push_str("  fi\n");
                }
            }
            output.push_str("}\n");

            if hook == "periodic" {
                output.push_str("zmodload zsh/datetime 2>/dev/null\n");
                for (event, module) in subs {
                    let interval: u64 = event
                        .split_once(':')
                        .and_then(|(_, second)| second.trim().parse().ok())
                        .unwrap_or(10);
                    output.push_str(&format!(
                        "_gai_last_run_{}_{}=0\n",
                        module.manifest.module.name, interval
                    ));
                }
                output.push_str("if [[ -z $PERIOD || $PERIOD -gt 1 ]]; then\n  PERIOD=1\nfi\n");
            }

            output.push_str(&format!("add-zsh-hook {} _gai_dispatch_{}\n\n", hook, hook));
        }
    }

    pub fn reset_fn(&self, modules: &[DiscoveredModule]) -> String {
        let mut output = String::new();
        output.push_str("_gai_reset() {\n");

        let mut functions: Vec<String> = Vec::new();
        let mut variables: Vec<String> = Vec::new();
        let mut aliases: Vec<String> = Vec::new();

        for module in modules {
            if module.status == ModuleStatus::Loaded {
                functions.extend(module.manifest.api.functions.iter().cloned());
                variables.extend(module.manifest.api.variables.iter().cloned());
                aliases.extend(module.manifest.api.aliases.keys().cloned());
                functions.extend(module.manifest.api.aliases.keys().cloned());

                let load_mode = module.manifest.load_mode();
                if load_mode != crate::core::manifest::LoadMode::Eager {
                    let loaded_var = format!("_gai_loaded_{}", module.manifest.module.name);
                    variables.push(loaded_var);
                    let loader_fn = format!("_gai_load_module_{}", module.manifest.module.name);
                    functions.push(loader_fn);
                }
            }
        }

        if !functions.is_empty() {
            output.push_str(&format!(
                "  unset -f {} 2>/dev/null\n",
                Helper::quote_escape(&functions)
            ));
        }

        if !variables.is_empty() {
            output.push_str(&format!(
                "  unset {} 2>/dev/null\n",
                Helper::quote_escape(&variables)
            ));
        }

        if !aliases.is_empty() {
            output.push_str(&format!(
                "  unalias {} 2>/dev/null\n",
                Helper::quote_escape(&aliases)
            ));
        }

        let mut active_hooks = BTreeSet::new();
        let mut periodic_vars = Vec::new();

        for module in modules {
            if module.status == ModuleStatus::Loaded
                && module.manifest.load_mode() == crate::core::manifest::LoadMode::Event
            {
                if let Some(ref load_meta) = module.manifest.load {
                    for event in &load_meta.events {
                        if event.starts_with("periodic") {
                            active_hooks.insert("periodic".to_string());
                            let interval: u64 = event
                                .split_once(':')
                                .and_then(|(_, second)| second.trim().parse().ok())
                                .unwrap_or(10);
                            periodic_vars.push(format!(
                                "_gai_last_run_{}_{}",
                                module.manifest.module.name, interval
                            ));
                        } else {
                            active_hooks.insert(event.clone());
                        }
                    }
                }
            }
        }

        if !active_hooks.is_empty() {
            output.push_str("  # --- Unregister Event Hooks ---\n");
            for hook in &active_hooks {
                output.push_str(&format!(
                    "  add-zsh-hook -d {} _gai_dispatch_{} 2>/dev/null\n",
                    hook, hook
                ));
            }

            let dispatchers: Vec<String> = active_hooks
                .iter()
                .map(|hook| format!("_gai_dispatch_{}", hook))
                .collect();
            output.push_str(&format!(
                "  unset -f {} 2>/dev/null\n",
                dispatchers.join(" ")
            ));
        }

        if !periodic_vars.is_empty() {
            output.push_str(&format!(
                "  unset {} 2>/dev/null\n",
                periodic_vars.join(" ")
            ));
        }

        output.push_str("}\n");
        output
    }
}

struct Helper;

impl Helper {
    fn quote_escape<Items, StrRef>(items: Items) -> String
    where
        Items: IntoIterator<Item = StrRef>,
        StrRef: AsRef<str>,
    {
        items
            .into_iter()
            .map(|string| format!("'{}'", Self::sq_escape(string.as_ref())))
            .collect::<Vec<_>>()
            .join(" ")
    }

    fn sq_escape(string: &str) -> String {
        string.replace('\'', r"'\''")
    }

    fn partition_stages(modules: &[DiscoveredModule]) -> Vec<Vec<&DiscoveredModule>> {
        let mut stages: Vec<Vec<&DiscoveredModule>> = Vec::new();
        let mut named = HashMap::new();

        for module in modules {
            if module.status != ModuleStatus::Loaded {
                continue;
            }

            let mut max_dep = 0;
            let mut has_dependencies = false;

            for dependency in &module.manifest.module.deps {
                if let Some(&stage_index) = named.get(dependency.name.as_str()) {
                    max_dep = max_dep.max(stage_index);
                    has_dependencies = true;
                }
            }

            let stage_index = if has_dependencies { max_dep + 1 } else { 0 };
            named.insert(module.manifest.module.name.as_str(), stage_index);

            while stages.len() <= stage_index {
                stages.push(Vec::new());
            }
            stages[stage_index].push(module);
        }
        stages
    }

    fn reset_fn(module: &DiscoveredModule) -> Option<String> {
        let api = &module.manifest.api;

        if Self::check_empty(api) {
            return None;
        }

        let mut output = String::new();
        output.push_str(&Self::reset_stub(&module.manifest.module.name));

        let functions: Vec<&str> = api
            .functions
            .iter()
            .map(String::as_str)
            .chain(api.aliases.keys().map(String::as_str))
            .collect();

        Self::emit_unset(&mut output, "unset -f", functions);
        Self::emit_unset(&mut output, "unset", &api.variables);
        Self::emit_unset(&mut output, "unalias", api.aliases.keys());

        output.push_str("}\n");
        Some(output)
    }

    fn emit_unset<Items, StrRef>(output: &mut String, command: &str, items: Items)
    where
        Items: IntoIterator<Item = StrRef>,
        StrRef: AsRef<str>,
    {
        let list: Vec<_> = items.into_iter().collect();
        if !list.is_empty() {
            output.push_str(&format!(
                "  {} {} 2>/dev/null\n",
                command,
                Self::quote_escape(list),
            ));
        }
    }

    fn module_loader(module: &DiscoveredModule) -> String {
        let mut output = String::new();
        let initialization = module.path.join("init.zsh");
        let loader_name = format!("_gai_load_module_{}", module.manifest.module.name);
        let loaded_flag = format!("_gai_loaded_{}", module.manifest.module.name);

        let mut unfunctions = Vec::new();
        unfunctions.extend(module.manifest.api.functions.iter().map(String::as_str));
        unfunctions.extend(module.manifest.api.completions.values().map(String::as_str));

        let mut unaliases = Vec::new();
        unaliases.extend(module.manifest.api.aliases.keys().map(String::as_str));

        output.push_str(&format!("{}=0\n", loaded_flag));
        output.push_str(&format!("{}() {{\n", loader_name));
        output.push_str(&format!(
            "  if (( {} == 1 )); then return; fi\n",
            loaded_flag
        ));
        output.push_str(&format!("  {}=1\n", loaded_flag));

        if !unfunctions.is_empty() {
            let list = Self::quote_escape(unfunctions);
            output.push_str(&format!("  unfunction {} 2>/dev/null\n", list));
        }
        if !unaliases.is_empty() {
            let list = Self::quote_escape(unaliases);
            output.push_str(&format!("  unalias {} 2>/dev/null\n", list));
        }

        output.push_str(&format!(
            "  source '{}'\n",
            Self::sq_escape(&initialization.display().to_string())
        ));

        for (name, expansion) in &module.manifest.api.aliases {
            output.push_str(&format!(
                "  alias '{}={}'\n",
                Self::sq_escape(name),
                Self::sq_escape(expansion)
            ));
        }
        output.push_str("}\n");

        Self::emit_stubs(&mut output, module, &loader_name);

        output
    }

    fn emit_stubs(output: &mut String, module: &DiscoveredModule, loader_name: &str) {
        let load_mode = module.manifest.load_mode();
        let lazy_mode = load_mode == crate::core::manifest::LoadMode::Lazy;
        let has_functions = !module.manifest.api.functions.is_empty();
        let has_aliases = !module.manifest.api.aliases.is_empty();

        if lazy_mode || has_functions || has_aliases {
            for function in &module.manifest.api.functions {
                let escaped = Self::sq_escape(function);
                output.push_str(&format!("unalias '{}' 2>/dev/null\n", escaped));
                output.push_str(&format!("{}() {{\n", escaped));
                output.push_str(&format!("  {}\n", loader_name));
                output.push_str(&format!("  '{}' \"$@\"\n", escaped));
                output.push_str("}\n");
            }

            for alias in module.manifest.api.aliases.keys() {
                let escaped = Self::sq_escape(alias);
                output.push_str(&format!("unalias '{}' 2>/dev/null\n", escaped));
                output.push_str(&format!("{}() {{\n", escaped));
                output.push_str(&format!("  {}\n", loader_name));
                output.push_str(&format!("  eval '{} \"$@\"'\n", escaped));
                output.push_str("}\n");
            }

            let mut completions = module.manifest.api.completions.values().collect::<Vec<_>>();
            completions.sort();
            completions.dedup();

            for completion in completions {
                let escaped = Self::sq_escape(completion);
                output.push_str(&format!("if ! type '{}' &>/dev/null; then\n", escaped));
                output.push_str(&format!("  unalias '{}' 2>/dev/null\n", escaped));
                output.push_str(&format!("  {}() {{\n", escaped));
                output.push_str(&format!("    unfunction '{}' 2>/dev/null\n", escaped));
                output.push_str(&format!("    {}\n", loader_name));
                output.push_str(&format!("    '{}' \"$@\"\n", escaped));
                output.push_str("  }\n");
                output.push_str("fi\n");
            }
        }
    }

    fn eager_loader(stage_index: usize, eager: &[&DiscoveredModule]) -> String {
        let mut output = String::new();

        if eager.is_empty() {
            return output;
        }

        output.push_str(&format!("# --- Stage {} ---\n", stage_index));
        for module in eager {
            let init_script = module.path.join("init.zsh");
            output.push_str(&format!(
                "source '{}'\n",
                Self::sq_escape(&init_script.display().to_string())
            ));

            for (name, expansion) in &module.manifest.api.aliases {
                output.push_str(&format!(
                    "alias '{}={}'\n",
                    Self::sq_escape(name),
                    Self::sq_escape(expansion)
                ));
            }
        }

        output
    }

    fn generate_completions(completions: &[String]) -> String {
        let mut output = String::new();

        if completions.is_empty() {
            return output;
        }

        output.push_str("\n# --- Completions ---\n");
        output.push_str("if type compdef &>/dev/null; then\n");
        for completion in completions {
            output.push_str(&format!("  {}\n", completion));
        }
        output.push_str("fi\n");
        output
    }

    fn check_empty(module_api: &ApiMeta) -> bool {
        module_api.functions.is_empty()
            && module_api.variables.is_empty()
            && module_api.aliases.is_empty()
    }

    fn reset_stub(name: &str) -> String {
        format!("_gai_reset_{}() {{\n", name)
    }

    fn render_wrapper() -> String {
        let bin = &&crate::core::common::exe_path();
        include_str!("../templates/wrapper.zsh").replace("{{GAIETY_BIN}}", bin)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::manifest::Manifest;
    use std::path::PathBuf;

    #[test]
    fn test_sq_escape() {
        assert_eq!(Helper::sq_escape("hello"), "hello");
        assert_eq!(Helper::sq_escape("don't"), r"don'\''t");
    }

    #[test]
    fn test_generate_reset_fn() {
        let loader = Loader { dirs: vec![] };
        let mut m = DiscoveredModule {
            path: PathBuf::from("/tmp"),
            manifest: Manifest::broken("test".to_string()),
            prefix_order: None,
            dir_index: 0,
            status: ModuleStatus::Loaded,
        };
        m.manifest.api.functions = vec!["foo".to_string()];
        m.manifest.api.variables = vec!["BAR".to_string()];

        let reset_script = loader.reset_fn(&[m]);
        assert!(reset_script.contains("unset -f 'foo'"));
        assert!(reset_script.contains("unset 'BAR'"));
    }
}
