use crate::manifest::Manifest;
use anyhow::{Context, Result};
use std::collections::HashMap;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

#[derive(Debug)]
pub struct DiscoveredModule {
    pub path: PathBuf,
    pub manifest: Manifest,
    pub prefix_order: Option<u32>,
    pub status: ModuleStatus,
}

#[derive(Debug, PartialEq)]
pub enum ModuleStatus {
    Loaded,
    SkippedMissingCmd(String),
}

pub struct Loader {
    dir: PathBuf,
}

impl Loader {
    pub fn new(dir: PathBuf) -> Self {
        Self { dir }
    }

    fn process_modules(&self) -> Result<Vec<DiscoveredModule>> {
        let mut modules = self.discover_modules()?;
        self.sort_modules(&mut modules);
        self.validate_commands(&mut modules);
        Ok(modules)
    }
 
    pub fn generate_init(&self) -> Result<String> {
        let modules = self.process_modules()?;
        let mut out = String::new();

        out.push_str("# Auto-generated by zrt-loader\n\n");
        out.push_str(&self.generate_reset_fn(&modules));
        out.push_str("\n# --- Load Modules ---\n");

        let mut all_completions = Vec::new();

        for m in &modules {
            if m.status == ModuleStatus::Loaded {
                let init_script = m.path.join("init.zsh");
                // Only source if init.zsh exists
                if init_script.exists() {
                    out.push_str(&format!("source {:?}\n", init_script.display()));
                }

                // Accumulate completions for later
                for (cmd, comp_fn) in &m.manifest.api.completions {
                    all_completions.push(format!("compdef {} {}", comp_fn, cmd));
                }
            }
        }

        if !all_completions.is_empty() {
            out.push_str("\n# --- Completions ---\n");
            out.push_str("if type compdef &>/dev/null; then\n");
            for comp in all_completions {
                out.push_str(&format!("  {}\n", comp));
            }
            out.push_str("fi\n");
        }

        Ok(out)
    }

    /// Prints a nice human-readable list of modules
    pub fn print_list(&self) -> Result<()> {
        let modules = self.process_modules()?;
        
        println!("\n\x1b[1;36m:: Module Registry\x1b[0m\n");
        
        for m in modules {
            let (status_color, status_text) = match &m.status {
                ModuleStatus::Loaded => ("\x1b[32m", "loaded"),
                ModuleStatus::SkippedMissingCmd(cmd) => {
                    ("\x1b[33m", "skipped")
                }
            };

            let deps = if m.manifest.module.deps.is_empty() {
                "[]".to_string()
            } else {
                format!("[{}]", m.manifest.module.deps.join(", "))
            };

            println!(
                "  \x1b[1;32m{:<14}\x1b[0m  {}{:<8}\x1b[0m  \x1b[2mv{:<7}\x1b[0m  deps:{:<22}  \x1b[2m{}\x1b[0m",
                m.manifest.module.name,
                status_color,
                status_text,
                m.manifest.module.version,
                deps,
                m.path.file_name().unwrap().to_string_lossy()
            );

            // Print why it was skipped if applicable
            if let ModuleStatus::SkippedMissingCmd(cmd) = &m.status {
                println!("    \x1b[33m↳ missing required command: {}\x1b[0m", cmd);
            }
        }
        println!();
        Ok(())
    }

    // --- Private Internal Helpers ---

    fn discover_modules(&self) -> Result<Vec<DiscoveredModule>> {
        let mut modules = Vec::new();
        if !self.dir.exists() {
            return Ok(modules);
        }

        for entry in fs::read_dir(&self.dir).context("Failed to read modules directory")? {
            let entry = entry?;
            let path = entry.path();

            if path.is_dir() {
                let toml_path = path.join("module.toml");
                if toml_path.exists() {
                    let content = fs::read_to_string(&toml_path)?;
                    let manifest: Manifest = toml::from_str(&content)?;

                    let dir_name = path.file_name().unwrap().to_string_lossy();
                    let prefix_order = dir_name.split('_').next().and_then(|s| s.parse::<u32>().ok());

                    modules.push(DiscoveredModule {
                        path,
                        manifest,
                        prefix_order,
                        status: ModuleStatus::Loaded,
                    });
                }
            }
        }
        Ok(modules)
    }

    fn sort_modules(&self, modules: &mut [DiscoveredModule]) {
        modules.sort_by(|a, b| match (a.prefix_order, b.prefix_order) {
            (Some(a_num), Some(b_num)) => a_num.cmp(&b_num),
            (Some(_), None) => std::cmp::Ordering::Less,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (None, None) => a.manifest.module.name.cmp(&b.manifest.module.name),
        });
    }

    fn validate_commands(&self, modules: &mut [DiscoveredModule]) {
        for m in modules.iter_mut() {
            for cmd in &m.manifest.module.requires_cmd {
                if !self.has_command(cmd) {
                    m.status = ModuleStatus::SkippedMissingCmd(cmd.clone());
                    break;
                }
            }
        }
    }

    fn has_command(&self, cmd: &str) -> bool {
        if let Ok(paths) = std::env::var("PATH") {
            for path in paths.split(':') {
                let p = Path::new(path).join(cmd);
                if p.is_file() {
                    if let Ok(meta) = p.metadata() {
                        if meta.permissions().mode() & 0o111 != 0 {
                            return true;
                        }
                    }
                }
            }
        }
        false
    }

    fn generate_reset_fn(&self, modules: &[DiscoveredModule]) -> String {
        let mut out = String::new();
        out.push_str("_zrt_reset() {\n");
        out.push_str("  # Suppress errors if already unset\n");

        let mut all_funcs = Vec::new();
        let mut all_vars = Vec::new();
        let mut all_aliases = Vec::new();

        for m in modules {
            if m.status == ModuleStatus::Loaded {
                all_funcs.extend(m.manifest.api.functions.clone());
                all_vars.extend(m.manifest.api.variables.clone());
                all_aliases.extend(m.manifest.api.aliases.keys().cloned());
            }
        }

        if !all_funcs.is_empty() {
            out.push_str(&format!("  unset -f {} 2>/dev/null\n", all_funcs.join(" ")));
        }
        if !all_vars.is_empty() {
            out.push_str(&format!("  unset {} 2>/dev/null\n", all_vars.join(" ")));
        }
        if !all_aliases.is_empty() {
            out.push_str(&format!("  unalias {} 2>/dev/null\n", all_aliases.join(" ")));
        }

        out.push_str("}\n");
        out
    }
}
